# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-11 17:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'MR', b'Monsieur'), (b'MISS', b'Mademoiselle'), (b'MRS', b'Madame')], default=b'MR', max_length=4, verbose_name=b'Civilit\xc3\xa9')),
                ('first_name', models.CharField(max_length=50, verbose_name=b'Pr\xc3\xa9nom')),
                ('last_name', models.CharField(max_length=50, verbose_name=b'Nom')),
                ('company', models.CharField(blank=True, max_length=50, verbose_name=b'Soci\xc3\xa9t\xc3\xa9')),
                ('address', models.CharField(max_length=255, verbose_name=b'Adresse')),
                ('additional_address', models.CharField(blank=True, max_length=255, verbose_name=b"Compl\xc3\xa9ment d'adresse")),
                ('postcode', models.CharField(max_length=5, verbose_name=b'Code postal')),
                ('city', models.CharField(max_length=50, verbose_name=b'Ville')),
                ('phone', models.CharField(max_length=10, verbose_name=b'T\xc3\xa9l\xc3\xa9phone')),
                ('mobilephone', models.CharField(blank=True, max_length=10, verbose_name=b'T\xc3\xa9l\xc3\xa9phone portable')),
                ('fax', models.CharField(blank=True, max_length=10, verbose_name=b'Fax')),
                ('workphone', models.CharField(blank=True, max_length=10, verbose_name=b'T\xc3\xa9l\xc3\xa9phone travail')),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='CartLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'verbose_name': "Ligne d'un panier client",
                'verbose_name_plural': "Lignes d'un panier client",
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=b'Nom de la cat\xc3\xa9gorie')),
                ('short_desc', models.CharField(blank=True, max_length=150, verbose_name=b'Description courte')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.Category', verbose_name=b'Cat\xc3\xa9gorie parente')),
            ],
            options={
                'verbose_name': 'Cat\xe9gorie de produits',
                'verbose_name_plural': 'Cat\xe9gories de produits',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_invoicing_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_invoicing_address', to='art.Address', verbose_name=b'Adresse de facturation par d\xc3\xa9faut')),
                ('default_shipping_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_shipping_address', to='art.Address', verbose_name=b'Adresse de livraison par d\xc3\xa9faut')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Utilisateur associe')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(auto_now=True, verbose_name=b'Date de la commande')),
                ('shipping_date', models.DateField(null=True, verbose_name=b"Date de l'exp\xc3\xa9dition")),
                ('status', models.CharField(choices=[(b'W', b'En attente de validation'), (b'P', b'Pay\xc3\xa9e'), (b'S', b'Exp\xc3\xa9di\xc3\xa9e'), (b'C', b'Annul\xc3\xa9e')], default=b'W', max_length=1, verbose_name=b'Statut de la commande')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=30, verbose_name=b'Identifiant de transaction Stripe')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Client', verbose_name=b'Client ayant pass\xc3\xa9 commande')),
                ('invoicing_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_invoicing_address', to='art.Address', verbose_name=b'Adresse de facturation')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipping_address', to='art.Address', verbose_name=b'Adresse de livraison')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(verbose_name=b'Quantit\xc3\xa9')),
                ('product_unit_price', models.FloatField(verbose_name=b'Prix unitaire du produit')),
                ('vat', models.FloatField(verbose_name=b'Taux de TVA')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Order', verbose_name=b'Commande associ\xc3\xa9e')),
            ],
            options={
                'verbose_name': "Ligne d'une commande",
                'verbose_name_plural': 'Lignes de commandes',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=b'commerce/media')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name=b'Nom du produit')),
                ('short_desc', models.CharField(max_length=150, verbose_name=b'Description courte')),
                ('long_desc', models.TextField(verbose_name=b'Description longue')),
                ('price', models.FloatField(verbose_name=b'Prix HT du produit')),
                ('thumbnail', models.ImageField(null=True, upload_to=b'commerce/media', verbose_name=b'Miniature du produit')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Category', verbose_name=b'Cat\xc3\xa9gorie du produit')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='VAT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.FloatField(verbose_name=b'Taux de TVA (d\xc3\xa9cimal)')),
            ],
            options={
                'verbose_name': 'Taux de TVA',
                'verbose_name_plural': 'Taux de TVA',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.VAT', verbose_name=b'Taux de TVA'),
        ),
        migrations.AddField(
            model_name='photo',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Product'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Product'),
        ),
        migrations.AddField(
            model_name='cartline',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Client'),
        ),
        migrations.AddField(
            model_name='cartline',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Product'),
        ),
        migrations.AddField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Client'),
        ),
    ]
