# Generated by Django 2.0.3 on 2018-04-22 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20180422_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartline',
            name='user',
        ),
    ]
